### ISSUE TITLE
Afterpay API error: Forbidden when saving config settings in Sandbox mode

### ISSUE THREAD

**Issue by techsteamdesk** [afterpay/afterpay-magento#12]
I've got this error appearing "Afterpay API error: Forbidden" when I try to save my settings in Sandbox mode - but I don't get this in Production mode.  Is there simply a different secret key for Sandbox mode, which my client should also have given me when they asked me to install and test this extension?  Or could it be part of a bigger problem, namely that the payment option is turned on, and does appear in the cart page, but does not appear when I am in the checkout process?  Any help you can offer will be much appreciated!

**Comment by stevenocta** [comment]
Hi Steam team,

Thank you for your Afterpay credential query.

There are two sets of credentials used throughout the standard Afterpay integration process. One set for the Afterpay sandbox account, and another for the Afterpay production account.

The 'Afterpay API Error: Forbidden' notification shared by your team is flagged when the credentials used are not correct against the current API Mode.

The item you've raised relates to a site-specific Afterpay integration, rather than that of a particular Afterpay-Magento plugin version.

Please liaise with your Afterpay Account Manager for assistance with your integration.

Thank you.
